version: '2'

services:

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - /etc/letsencrypt/live/ec.satoshi.tech/privkey.pem:/etc/nginx/ec.satoshi.tech/privkey.pem
      - /etc/letsencrypt/live/ec.satoshi.tech/fullchain.pem:/etc/nginx/ec.satoshi.tech/fullchain.pem
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
    restart: always

  ghost:
    build: ./ghost
    volumes:
      - ghost:/var/lib/ghost
    # - $PWD/ghost/config.js:/var/lib/ghost/config.js
    ports: 
      - "2368:2368"
    environment:
      - NODE_ENV=production
    #command: bash -c "sleep 5s; npm start --production"
    restart: always

volumes:
  ghost:
